---

- name: Download NeoFS S3 GW binary 
  ansible.builtin.include_role:
    name: nspcc.ansible_goodies.github
  vars:
    github__org: '{{ neofs_s3__github_org }}'
    github__repo: '{{ neofs_s3__github_repo }}'
    github__version: '{{ neofs_s3__version }}'
    github__asset_name: '{{ neofs_s3__gw_github_asset_name }}'
    github__args:
      dest: '{{ neofs_s3__bin_path }}'
      owner: 'root'
      group: 'root'
      mode: '0755'
      force: yes
    github__notify: [ 'Restart NeoFS S3 service' ]
