---

- name: Copy NeoFS S3 wallet
  ansible.builtin.copy:
    content: '{{ neofs_s3__wallet }}'
    dest: '{{ neofs_s3__wallet_path }}'
    owner: 'root'
    group: '{{ neofs_s3__group }}'
    mode: '0640'
  notify: [ 'Restart NeoFS S3 service' ]
