---

- name: Copy NeoFS IR wallet
  ansible.builtin.copy:
    src: '{{ neofs_ir__wallet }}'
    dest: '{{ neofs_ir__wallet_path }}'
    owner: 'root'
    group: '{{ neofs_ir__group }}'
    mode: '0640'
  notify: [ 'Restart NeoFS IR' ]
